# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go+

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go+
        uses: goplus/setup-goplus@v1.1.0
        with:
          go-version: "1.21"
          gop-version: "not-exists"

      - name: Build
        run: gop build -v ./...

      - name: Test
        run: gop test -v ./...

      - name: Run
        run: gop run .

      - name: Install
        run: gop install ./...
